# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E_Rp7yyh26-eRV6QgbH2GPmJlzfTCcVw
"""

import pandas as pd
Oqituvchilar=pd.DataFrame ( {

                           "F.I.Sh":[ 'Qadamova Z.E.','Jorayva G.F.','Xontorayev S.I.','Qurbonova G.M.','Djalilov M.L.','Rahmatov R.R.','Tillaboyev M.G.','Turdimatov M.M.','Xalilov D.A.','Abdullayeva M.R.'  ],
                           "Fani":['Suniy intellek asoalari','Elektronika va sxemalar','Malumotlar tuzilmasi va algoritimlari','Kopyuterni tashkil etish','Kopyuterni tashkil etish','Kiberxavfsizlik asoslar','Elektronika va sxemalar','Kiberxavfsizlik asoslar','Suniy intellek asoalari','Malumotlar tuzilmasi va algoritimlari'],
                 "Mashgulot  turi":['amaliy', 'maruza','maruza','amaliy','maruza','amaliy','amaliy','maruza','maruza','amaily'],
                           "my_respect":['xa','xa','xa','xa','xa','xa','xa','xa','xa','xa',]

})
print(Oqituvchilar)

Oqituvchilar.to_excel('Oqituvchilar 680-23.xlsx')